const matches = [
  {
    id: 2,
    eventId: "54event\u00014ac4b69a0-0ab1-41b4-9de0-4ed3eb34d514\u0001\u0001",
    blueTeamTop: '2381C',
    blueTeamBottom: '2381Y',
    redTeamTop: '4862B',
    redTeamBottom: '905A',
    blueScore: 19,
    redScore: 24,
  },
  {
    id: 3,
    eventId: "54event\u00014ac4b69a0-0ab1-41b4-9de0-4ed3eb34d514\u0001\u0001",
    blueTeamTop: '5225A',
    blueTeamBottom: '1104V',
    redTeamTop: '4862B',
    redTeamBottom: '905A',
    blueScore: 60,
    redScore: 58,
  },
];

const events = [
  {
    id: 1,
    eventName: 'Lockheed Martin VEX EDR Qualifying Event ',
    eventLocation: '149 Berrigan Dr., Ottawa, Ontario',
    eventType: 'Tournament',
    eventDate: '2020-01-11',
    numberOfMatches: 5,
  },
  {
    id: 2,
    eventName: 'Massey Vanier VEX EDR Qualifying Event ',
    eventLocation: '222, Rue Mercier, Cowansville, Quebec',
    eventType: 'Tournament',
    eventDate: '2020-01-11',
    numberOfMatches: 5,
  },
  {
    id: 3,
    eventName: 'Vex Ontario Provincial Championship ',
    eventLocation: '15 Glenview Avenue, St. Catharines, Ontario',
    eventType: 'Tournament',
    eventDate: '2020-01-11',
    numberOfMatches: 5,
  },
];

const chart = [
  1.1,
  3,
  1.5,
  2.3,
  3.2,
  7,
  8.2,
  1.2,
  2,
  1.2,
  8,
  3.8,
  5.8,
  3.9,
  5.1,
  0.1,
  6,
];

const user = {
  _id : '1', 
  userName: "C9WIN",
  fullName : "Cloud9BestTeam",
  team : "CLOUD9",
  avatar: require('./assets/avatar.png'),
};

const userTeam = {
    key:1,
    teamOrg: "2381",
    teamLetter : "Y",
    teamName: "Kernel Bye",
    location : "Ottawa, Ontario, Canada",
    tournamentsAttended : 5,
    averagePlacement : 10,
    totalAwards : 1,
    averagePPG : 60,
    averagePPGAgainst: 45,
    bestDriverScore : 90,
    bestProgrammingScore: 5,
    skillsRanking: 218,
}

const teams = [
  {
    key:1,
    teamOrg: "2381",
    teamLetter : "W",
    teamName: "Kernel Bye ω",
    location : "Ottawa, Ontario, Canada",
    tournamentsAttended : 4,
    averagePlacement : 9,
    totalAwards : 1,
    averagePPG : 65,
    averagePPGAgainst: 35,
    bestDriverScore : 130,
    bestProgrammingScore: 5,
    skillsRanking: 38,
    favourite:true,
  },
  {
    key:4,
    teamOrg: "905",
    teamLetter : "A",
    teamName: "#RIPWORLDS2020",
    location : "Toronto, Ontario, Canada",
    tournamentsAttended : 6,
    averagePlacement : 6,
    totalAwards : 5,
    averagePPG : 70,
    averagePPGAgainst: 40,
    bestDriverScore : 120,
    bestProgrammingScore:20,
    skillsRanking: 28,
    favourite:false,
  },
  {
    key:3,
    teamOrg: "5225",
    teamLetter : "A",
    teamName: "E-Bots PiLons",
    location : "Oakville, Ontario, Canada",
    tournamentsAttended : 7,
    averagePlacement : 1,
    totalAwards : 9,
    averagePPG : 65,
    averagePPGAgainst: 30,
    bestDriverScore : 168,
    bestProgrammingScore: 90,
    skillsRanking: 2,
    favourite:false,
  },
  {
    key:2,
    teamOrg: "1104",
    teamLetter : "Z",
    teamName: "Discobots ζ",
    location : "Brampton, Ontario, Canada",
    tournamentsAttended : 6,
    averagePlacement : 6,
    totalAwards : 5,
    averagePPG : 60,
    averagePPGAgainst: 30,
    bestDriverScore : 90,
    bestProgrammingScore: 5,
    skillsRanking: 100,
    favourite:false,
  },
  {
    key:5,
    teamOrg: "4862",
    teamLetter : "B",
    teamName: "Coltenoids Banana",
    location : "Ottawa, Ontario, Canada",
    tournamentsAttended : 6,
    averagePlacement : 6,
    totalAwards : 6,
    averagePPG : 80,
    averagePPGAgainst: 26,
    bestDriverScore : 100,
    bestProgrammingScore: 20,
    skillsRanking: 87,
    favourite:true,
  },
]

export {matches, events, chart, user, teams, userTeam};
